Predict the class of the flower based on available attributes

In [23]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

Import Iris Dataset

In [35]:
iris_dataset=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data',header=None)## header=None given as it ignores the first row of the table to be the header
iris_dataset.head()

     0    1    2    3            4
0  5.1  3.5  1.4  0.2  Iris-setosa
1  4.9  3.0  1.4  0.2  Iris-setosa
2  4.7  3.2  1.3  0.2  Iris-setosa
3  4.6  3.1  1.5  0.2  Iris-setosa
4  5.0  3.6  1.4  0.2  Iris-setosa

Rename columns of the iris dataset

In [4]:
columns=['sepal length','sepal width','petal length','petal width','class']
iris_dataset.columns=columns

In [5]:
iris_dataset.head()

   sepal length  sepal width  petal length  petal width        class
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

Use fit_tranform method of Label Encoder class to convert the values of the column "class" into discrete values

In [7]:
enc=LabelEncoder()

In [11]:
iris_dataset['class']=enc.fit_transform(iris_dataset['class'])

In [12]:
iris_dataset.head()

   sepal length  sepal width  petal length  petal width  class
0           5.1          3.5           1.4          0.2      0
1           4.9          3.0           1.4          0.2      0
2           4.7          3.2           1.3          0.2      0
3           4.6          3.1           1.5          0.2      0
4           5.0          3.6           1.4          0.2      0

1.Now we import the train_test_split method to iris dataset to split into train and test set.
2.test_size=0.2 means 20% of the entire dataset randomly will be used as a test set
3.random_state is used for choosing train set randomly..If not used the dataset splitting will not be done randomly.

In [25]:
train,test=train_test_split(iris_dataset,test_size=0.2,random_state=0)

Now we need to separate the X and target attributes(Y) in both train and test set

In [26]:
train_Y=train['class']
train_X=train.drop(columns=['class'],axis=1)

In [27]:
train_X.head()

     sepal length  sepal width  petal length  petal width
137           6.4          3.1           5.5          1.8
84            5.4          3.0           4.5          1.5
27            5.2          3.5           1.5          0.2
127           6.1          3.0           4.9          1.8
132           6.4          2.8           5.6          2.2

In [28]:
train_Y.head()

137    2
84     1
27     0
127    2
132    2
Name: class, dtype: int64

In [29]:
test_Y=test['class']
test_X=test.drop(columns=['class'],axis=1)

Import the class Logistic regression to call the methods

In [30]:
lr=LogisticRegression()

Train the model by using the fit method of Logisitic Regression class.

In [31]:
lr.fit(train_X,train_Y)

/opt/conda/envs/Python36/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/opt/conda/envs/Python36/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

Predict the Y from the test set using the trained model

In [33]:
predict_test_Y=lr.predict(test_X)

Calculate the accuracy score with predicted Y of the test set and actual Y  values of the test set.

In [34]:
score=accuracy_score(predict_test_Y,test_Y)
print("Score of the model is",score)

Score of the model is 0.9666666666666667